export { default as StyledImage } from './image.styles'
export { default as StyledLink } from './link.styles'
export { default as StyledContainer } from './container.styles'
export { default as StyledMainContent } from './mainContent.styles'
export { default as StyledSubContent } from './subContent.styles'
export { default as StyledForm} from './form.styles'
export { default as StyledInput } from './input.styles'
export { default as StyledButton } from './button.styles'